# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: itcmedia
service: markdown-portal-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1 # お好みのAWSリージョン
  stage: dev
  environment:
    DB_CONNECTION_STRING: "your-database-connection-string" # 必要に応じて設定

functions:
  docsHandler:
    handler: src/index.handler
    events:
      - http:
          path: api/docs
          method: get
      - http:
          path: api/docs/{slug}
          method: get
      - http:
          path: api/docs
          method: post
      - http:
          path: api/docs/{slug}
          method: put
      - http:
          path: api/docs/{slug}
          method: delete
      - http:
          path: api/documents/{slug}
          method: get


plugins:
  - serverless-offline # ローカル環境でのテスト用
