name: CI/CD for Backend

on:
  # develop/main ブランチへの push でデプロイ
  push:
    branches:
      - develop
      - main

  # プルリクエスト時はテストのみ
  pull_request:
    branches:
      - develop
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1) コードをチェックアウト
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Node.js のセットアップ
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) 依存パッケージをインストール
      - name: Install dependencies
        run: |
          cd backend
          npm ci

      # 4) テスト実行
      - name: Run tests
        run: |
          cd backend
          npm run test

      # 5) AWS 認証 (push の場合のみ) → これ以降で serverless deploy
      - name: Configure AWS Credentials
        if: ${{ github.event_name == 'push' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6) デプロイ (develop → dev / main → prod)
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: |
          cd backend
          if [ "${{ github.ref_name }}" = "develop" ]; then
            echo "Deploying to dev stage..."

            # 環境変数をGitHub Secretsからexport → serverless.yml が ${env:...} 参照
            export DEV_COGNITO_REGION="${{ secrets.DEV_COGNITO_REGION }}"
            export DEV_COGNITO_USER_POOL_ID="${{ secrets.DEV_COGNITO_USER_POOL_ID }}"
            export DEV_COGNITO_DOMAIN="${{ secrets.DEV_COGNITO_DOMAIN }}"
            export DEV_COGNITO_CLIENT_ID="${{ secrets.DEV_COGNITO_CLIENT_ID }}"
            export DEV_SIGNIN_URL="${{ secrets.DEV_SIGNIN_URL }}"
            export DEV_SIGNOUT_URL="${{ secrets.DEV_SIGNOUT_URL }}"
            export S3_STAGING_BUCKET="${{ secrets.S3_STAGING_BUCKET }}"
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}"

            serverless deploy --stage dev

          elif [ "${{ github.ref_name }}" = "main" ]; then
            echo "Deploying to prod stage..."

            export PROD_COGNITO_REGION="${{ secrets.PROD_COGNITO_REGION }}"
            export PROD_COGNITO_USER_POOL_ID="${{ secrets.PROD_COGNITO_USER_POOL_ID }}"
            export PROD_COGNITO_DOMAIN="${{ secrets.PROD_COGNITO_DOMAIN }}"
            export PROD_COGNITO_CLIENT_ID="${{ secrets.PROD_COGNITO_CLIENT_ID }}"
            export PROD_SIGNIN_URL="${{ secrets.PROD_SIGNIN_URL }}"
            export PROD_SIGNOUT_URL="${{ secrets.PROD_SIGNOUT_URL }}"
            export S3_PROD_BUCKET="${{ secrets.S3_PROD_BUCKET }}"
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}"

            serverless deploy --stage prod

          else
            echo "Not on develop or main. Skipping deploy."
          fi
